# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
    ]
