# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20170928_1612'),
        ('restaurants', '0010_restaurantlocation_owner'),
    ]

    operations = [
    ]
