# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_item_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
